#!/usr/bin/env bash
# Mission Control — Install Script
# For OpenClaw users who want a multi-agent orchestration dashboard.
#
# What this does:
#   1. Checks prerequisites (Node.js, OpenClaw)
#   2. Installs npm dependencies & builds
#   3. Auto-detects OpenClaw gateway config (token, URL)
#   4. Generates .env.local with secure defaults
#   5. Sets up mc.sh CLI wrapper
#   6. Optionally creates a systemd service
#   7. Creates default agents (Scout, Writer, Analyst, Ops)
#
# Usage:
#   git clone https://github.com/kalichkin/mission-control.git
#   cd mission-control
#   bash install.sh

set -euo pipefail

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()    { echo -e "${GREEN}✓${NC}  $*"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
fail()  { echo -e "${RED}✗${NC}  $*"; exit 1; }
ask()   { echo -en "${BOLD}?${NC}  $* "; }

MC_DIR="$(cd "$(dirname "$0")" && pwd)"
MC_PORT="${MC_PORT:-4000}"

echo ""
echo -e "${BOLD}🦞 Mission Control — Installer${NC}"
echo -e "   AI Agent Orchestration Dashboard"
echo ""

# --- Step 1: Prerequisites ---
info "Checking prerequisites..."

command -v node >/dev/null 2>&1 || fail "Node.js not found. Install v18+: https://nodejs.org/"
NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
[[ "$NODE_VER" -ge 18 ]] || fail "Node.js v18+ required (found v$NODE_VER)"
ok "Node.js $(node -v)"

command -v npm >/dev/null 2>&1 || fail "npm not found"
ok "npm $(npm -v)"

# Check for OpenClaw
OPENCLAW_CONFIG=""
for cfg in "$HOME/.openclaw/openclaw.json" "/root/.openclaw/openclaw.json"; do
  [[ -f "$cfg" ]] && OPENCLAW_CONFIG="$cfg" && break
done

if [[ -n "$OPENCLAW_CONFIG" ]]; then
  ok "OpenClaw config found: $OPENCLAW_CONFIG"
else
  warn "OpenClaw config not found. You'll need to configure manually."
fi

echo ""

# --- Step 2: Install & Build ---
info "Installing dependencies..."
cd "$MC_DIR"
npm install --production=false 2>&1 | tail -1
ok "Dependencies installed"

info "Building for production..."
npm run build 2>&1 | tail -1
ok "Build complete"

echo ""

# --- Step 3: Configure ---
info "Setting up configuration..."

# Auto-detect OpenClaw settings
GW_TOKEN=""
GW_URL="ws://127.0.0.1:18789"

if [[ -n "$OPENCLAW_CONFIG" ]] && command -v node >/dev/null 2>&1; then
  GW_TOKEN=$(node -e "
    try {
      const c = require('$OPENCLAW_CONFIG');
      const t = c.gateway?.token || c.gatewayToken || '';
      process.stdout.write(t);
    } catch(e) {}
  " 2>/dev/null || true)

  DETECTED_URL=$(node -e "
    try {
      const c = require('$OPENCLAW_CONFIG');
      const p = c.gateway?.port || c.gatewayPort || 18789;
      process.stdout.write('ws://127.0.0.1:' + p);
    } catch(e) {}
  " 2>/dev/null || true)
  [[ -n "$DETECTED_URL" ]] && GW_URL="$DETECTED_URL"
fi

if [[ -n "$GW_TOKEN" ]]; then
  ok "Auto-detected gateway token from OpenClaw config"
else
  warn "Could not detect gateway token."
  ask "Enter your OpenClaw gateway token (from openclaw.json):"
  read -r GW_TOKEN
  [[ -z "$GW_TOKEN" ]] && fail "Gateway token is required"
fi

# Generate MC API token
MC_API_TOKEN=$(openssl rand -hex 32)
ok "Generated API token for Mission Control"

# Generate webhook secret
WEBHOOK_SECRET=$(openssl rand -hex 32)

# Write .env.local
if [[ -f "$MC_DIR/.env.local" ]]; then
  warn ".env.local already exists — backing up to .env.local.bak"
  cp "$MC_DIR/.env.local" "$MC_DIR/.env.local.bak"
fi

cat > "$MC_DIR/.env.local" << EOF
# Mission Control Configuration (auto-generated by install.sh)
# $(date -u +"%Y-%m-%d %H:%M UTC")

DATABASE_PATH=./mission-control.db
OPENCLAW_GATEWAY_URL=$GW_URL
OPENCLAW_GATEWAY_TOKEN=$GW_TOKEN
MC_API_TOKEN=$MC_API_TOKEN
WEBHOOK_SECRET=$WEBHOOK_SECRET
EOF

chmod 600 "$MC_DIR/.env.local"
ok "Created .env.local (chmod 600)"

echo ""

# --- Step 4: mc.sh CLI setup ---
info "Setting up mc.sh CLI wrapper..."

WORKSPACE_DIR=""
for ws in "$HOME/.openclaw/workspace" "/root/.openclaw/workspace"; do
  [[ -d "$ws" ]] && WORKSPACE_DIR="$ws" && break
done

if [[ -n "$WORKSPACE_DIR" ]]; then
  mkdir -p "$WORKSPACE_DIR/tools"
  # Copy mc.sh but strip any hardcoded tokens
  sed \
    -e "s|MC_URL=.*|MC_URL=\"\${MISSION_CONTROL_URL:-http://localhost:$MC_PORT}\"|" \
    -e "s|MC_TOKEN=.*|MC_TOKEN=\"\${MISSION_CONTROL_TOKEN:-$MC_API_TOKEN}\"|" \
    -e "s|MC_WORKSPACE=.*|MC_WORKSPACE=\"\${MISSION_CONTROL_WORKSPACE:-}\"|" \
    "$MC_DIR/scripts/mc.sh" > "$WORKSPACE_DIR/tools/mc.sh"
  chmod +x "$WORKSPACE_DIR/tools/mc.sh"
  ok "mc.sh installed to $WORKSPACE_DIR/tools/mc.sh"
else
  warn "OpenClaw workspace not found. Copy scripts/mc.sh manually to your workspace/tools/"
fi

echo ""

# --- Step 5: systemd service (optional) ---
if [[ "$(id -u)" == "0" ]] && command -v systemctl >/dev/null 2>&1; then
  ask "Create systemd service? (y/N)"
  read -r CREATE_SERVICE
  if [[ "$CREATE_SERVICE" =~ ^[Yy] ]]; then
    cat > /etc/systemd/system/mission-control.service << EOF
[Unit]
Description=Mission Control Dashboard
After=network.target

[Service]
Type=simple
WorkingDirectory=$MC_DIR
ExecStart=$(command -v npx) next start -p $MC_PORT -H 0.0.0.0
Restart=always
RestartSec=5
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable mission-control
    ok "systemd service created and enabled"

    ask "Start Mission Control now? (Y/n)"
    read -r START_NOW
    if [[ ! "$START_NOW" =~ ^[Nn] ]]; then
      systemctl start mission-control
      ok "Mission Control started on port $MC_PORT"
    fi
  fi
else
  info "Run manually: cd $MC_DIR && npx next start -p $MC_PORT"
fi

echo ""

# --- Step 6: Create default agents ---
info "Setting up default agents..."

# Wait for MC to be up
MC_BASE="http://localhost:$MC_PORT"
MC_UP=false
for i in $(seq 1 10); do
  if curl -sf "$MC_BASE/api/health" -H "Authorization: Bearer $MC_API_TOKEN" >/dev/null 2>&1 || \
     curl -sf "$MC_BASE/api/agents" -H "Authorization: Bearer $MC_API_TOKEN" >/dev/null 2>&1; then
    MC_UP=true
    break
  fi
  sleep 1
done

if $MC_UP; then
  # Get workspace ID
  WS_ID=$(curl -sf "$MC_BASE/api/workspaces" -H "Authorization: Bearer $MC_API_TOKEN" 2>/dev/null | \
    node -e "try{const d=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));console.log(d[0]?.id||d.id||'')}catch(e){}" 2>/dev/null || true)

  if [[ -z "$WS_ID" ]]; then
    # Create a workspace
    WS_ID=$(curl -sf -X POST "$MC_BASE/api/workspaces" \
      -H "Authorization: Bearer $MC_API_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{"name":"Main Workspace"}' 2>/dev/null | \
      node -e "try{const d=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));console.log(d.id||'')}catch(e){}" 2>/dev/null || true)
  fi

  if [[ -n "$WS_ID" ]]; then
    ok "Workspace: $WS_ID"

    # Update mc.sh with workspace ID
    if [[ -n "$WORKSPACE_DIR" ]] && [[ -f "$WORKSPACE_DIR/tools/mc.sh" ]]; then
      sed -i "s|MC_WORKSPACE=.*|MC_WORKSPACE=\"\${MISSION_CONTROL_WORKSPACE:-$WS_ID}\"|" "$WORKSPACE_DIR/tools/mc.sh"
    fi

    # Default agents
    DEFAULT_AGENTS='[
      {"name":"Scout","avatar_emoji":"🔍","openclaw_agent_id":"scout","status":"standby"},
      {"name":"Writer","avatar_emoji":"✍️","openclaw_agent_id":"writer","status":"standby"},
      {"name":"Analyst","avatar_emoji":"📊","openclaw_agent_id":"analyst","status":"standby"},
      {"name":"Ops","avatar_emoji":"🔧","openclaw_agent_id":"ops","status":"standby"}
    ]'

    # Check existing agents
    EXISTING=$(curl -sf "$MC_BASE/api/agents?workspace_id=$WS_ID" \
      -H "Authorization: Bearer $MC_API_TOKEN" 2>/dev/null | \
      node -e "try{const d=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));console.log(d.length||0)}catch(e){console.log(0)}" 2>/dev/null || echo "0")

    if [[ "$EXISTING" == "0" ]]; then
      echo "$DEFAULT_AGENTS" | node -e "
        const agents = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
        const http = require('http');
        agents.forEach(a => {
          const data = JSON.stringify({...a, workspace_id: '$WS_ID'});
          const req = http.request({
            hostname: 'localhost', port: $MC_PORT, path: '/api/agents',
            method: 'POST', headers: {
              'Content-Type': 'application/json',
              'Authorization': 'Bearer $MC_API_TOKEN',
              'Content-Length': data.length
            }
          }, res => {
            let body = '';
            res.on('data', c => body += c);
            res.on('end', () => console.log('  Created: ' + a.avatar_emoji + ' ' + a.name));
          });
          req.write(data);
          req.end();
        });
      " 2>/dev/null
      sleep 1
      ok "Default agents created (Scout, Writer, Analyst, Ops)"
    else
      ok "Agents already exist ($EXISTING found), skipping"
    fi
  else
    warn "Could not detect workspace ID. Create agents manually in the UI."
  fi
else
  warn "Mission Control not yet running. Start it and agents will need to be created via UI."
  info "Or re-run this script after starting the service."
fi

echo ""

# --- Done ---
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}  🦞 Mission Control is ready!${NC}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  Dashboard:  ${BOLD}http://localhost:$MC_PORT${NC}"
echo -e "  API Token:  ${BOLD}${MC_API_TOKEN:0:12}...${NC} (in .env.local)"
[[ -n "${WS_ID:-}" ]] && echo -e "  Workspace:  ${BOLD}$WS_ID${NC}"
echo ""
echo -e "  ${BLUE}Agents:${NC} Scout 🔍, Writer ✍️, Analyst 📊, Ops 🔧"
echo ""
echo -e "  To map agents to your OpenClaw agent IDs,"
echo -e "  edit them in the UI or update openclaw_agent_id via API."
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Open the dashboard and verify agents are visible"
echo -e "    2. Create your first task"
echo -e "    3. Add mc.sh commands to your AGENTS.md"
echo ""
